In [1]:
from data_imports import *
from compare_data import *

In [2]:
# Database request of city/kanton level
cityZH = import_cityZH_api()
print("City of Zurich")
#cityZH['date'] = cityZH['date'].dt.date
print(cityZH.head())

kantonZH = import_kantonZH_api()
print("Kanton data")
print(kantonZH.head())
#kantonZH['date'] = kantonZH['date'].dt.date
# Network requests
geoadmin = import_geoadmin_wikidata_kt()
print("Kanton geo.admin.data")
print(geoadmin.head())
#geoadmin['date'] = geoadmin['date'].dt.date
wikidataKT = import_wikidata_kt()
print("Wikidata for Kanton")
print(wikidataKT.head())
#wikidataKT['date'] = wikidataKT['date'].dt.date
wikidataGM = import_wikidata_qt()
print("Wikidata for Quartier")
print(wikidataGM.head())

City of Zurich
    id        name        date population wikidata_id
0  123  Hirzenbach  2018-12-31      12801     Q693374
1  123  Hirzenbach  2017-12-31      12627     Q693374
2  123  Hirzenbach  2016-12-31      12463     Q693374
3  123  Hirzenbach  2015-12-31      11930     Q693374
4  123  Hirzenbach  2014-12-31      11679     Q693374
Kanton data
   BFS_NR     GEBIET_NAME        date  population
0      21         Adlikon  2018-12-31       707.0
1     131        Adliswil  2018-12-31     18681.0
2     241        Aesch ZH  2018-12-31      1555.0
3       1     Aeugst a.A.  2018-12-31      1979.0
4       2  Affoltern a.A.  2018-12-31     12201.0
Kanton geo.admin.data
            Name  bfs wikidata_id
0      Ottenbach   11      Q67513
1  Wetzikon (ZH)  121      Q68305
2       Adliswil  131      Q68210
3      Stallikon   13      Q66062
4        Thalwil  141      Q68959
Wikidata for Kanton
  wikidata_id  bfs_id        date population      qualifier
0     Q218691     161  2017-12-31      12983     NormalRank
1     Q218691     161  2018-12-31      13008     NormalRank
2      Q67310     119  2017-01-01       1426  PreferredRank
3      Q67310     119  2017-12-31       1440     NormalRank
4      Q67310     119  2018-12-31       1442     NormalRank
Wikidata for Quartier
  wikidata_id        date population      qualifier
0     Q276792  2014-12-31      24431     NormalRank
1     Q276792  1974-12-31      19761     NormalRank
2     Q276792  1973-12-31      19729     NormalRank
3     Q276792  1976-12-31      19151     NormalRank
4     Q276792  2017-12-31      25817  PreferredRank

In [3]:
# 1. Join Q_Numbers
# wikidata_id
print("MERGER")
merger = pd.merge(kantonZH, geoadmin, how='left', left_on=['BFS_NR'], right_on=['bfs']).dropna()
print(merger.head())

MERGER
   BFS_NR     GEBIET_NAME        date  population                Name    bfs  \
0      21         Adlikon  2018-12-31       707.0             Adlikon   21.0
1     131        Adliswil  2018-12-31     18681.0            Adliswil  131.0
2     241        Aesch ZH  2018-12-31      1555.0          Aesch (ZH)  241.0
3       1     Aeugst a.A.  2018-12-31      1979.0     Aeugst am Albis    1.0
4       2  Affoltern a.A.  2018-12-31     12201.0  Affoltern am Albis    2.0

  wikidata_id
0      Q68356
1      Q68210
2      Q68342
3      Q64945
4      Q68290

In [4]:
merger['check'] = merger['date'].astype(str) + '---' + merger['BFS_NR'].astype(str)
print(merger['check'].head())
print()
wikidataKT['check'] = wikidataKT['date'].astype(str) + '---' + wikidataKT['bfs_id'].astype(str)
print(wikidataKT['check'].head())
print("NOT IN THE DATASET")
print(len(merger[(merger['check'].isin(wikidataKT['check']) == False)].index.tolist()))
merger['bool'] = merger['check'].isin(wikidataKT['check'])

0     2018-12-31---21
1    2018-12-31---131
2    2018-12-31---241
3      2018-12-31---1
4      2018-12-31---2
Name: check, dtype: object

0    2017-12-31---161
1    2018-12-31---161
2    2017-01-01---119
3    2017-12-31---119
4    2018-12-31---119
Name: check, dtype: object
NOT IN THE DATASET
8867

In [5]:
merger[(merger['wikidata_id']=='Q68959')==True].head(20)

,BFS_NR,GEBIET_NAME,date,population,Name,bfs,wikidata_id,check,bool
142,141,Thalwil,2018-12-31,17964.0,Thalwil,141.0,Q68959,2018-12-31---141,True
318,141,Thalwil,2017-12-31,17784.0,Thalwil,141.0,Q68959,2017-12-31---141,True
494,141,Thalwil,2016-12-31,17728.0,Thalwil,141.0,Q68959,2016-12-31---141,False
670,141,Thalwil,2015-12-31,17729.0,Thalwil,141.0,Q68959,2015-12-31---141,False
846,141,Thalwil,2014-12-31,17610.0,Thalwil,141.0,Q68959,2014-12-31---141,False
1022,141,Thalwil,2013-12-31,17496.0,Thalwil,141.0,Q68959,2013-12-31---141,False
1198,141,Thalwil,2012-12-31,17309.0,Thalwil,141.0,Q68959,2012-12-31---141,True
1374,141,Thalwil,2011-12-31,17256.0,Thalwil,141.0,Q68959,2011-12-31---141,False
1550,141,Thalwil,2010-12-31,17189.0,Thalwil,141.0,Q68959,2010-12-31---141,False
1726,141,Thalwil,2009-12-31,16832.0,Thalwil,141.0,Q68959,2009-12-31---141,False
1902,141,Thalwil,2008-12-31,16607.0,Thalwil,141.0,Q68959,2008-12-31---141,False
2078,141,Thalwil,2007-12-31,16427.0,Thalwil,141.0,Q68959,2007-12-31---141,False
2254,141,Thalwil,2006-12-31,16215.0,Thalwil,141.0,Q68959,2006-12-31---141,False
2430,141,Thalwil,2005-12-31,16281.0,Thalwil,141.0,Q68959,2005-12-31---141,False
2606,141,Thalwil,2004-12-31,16206.0,Thalwil,141.0,Q68959,2004-12-31---141,False
2782,141,Thalwil,2003-12-31,16037.0,Thalwil,141.0,Q68959,2003-12-31---141,False
2958,141,Thalwil,2002-12-31,15926.0,Thalwil,141.0,Q68959,2002-12-31---141,False
3134,141,Thalwil,2001-12-31,15851.0,Thalwil,141.0,Q68959,2001-12-31---141,False
3310,141,Thalwil,2000-12-31,15749.0,Thalwil,141.0,Q68959,2000-12-31---141,False
3486,141,Thalwil,1999-12-31,15767.0,Thalwil,141.0,Q68959,1999-12-31---141,False

In [6]:
cityZH.head()
cityZH['check'] = cityZH['date'].astype(str) + '---' + cityZH['wikidata_id'].astype(str)
wikidataGM['check'] = wikidataGM['date'].astype(str) + '---' + wikidataGM['wikidata_id'].astype(str)

print(cityZH['check'].head())
print("NOT IN THE DATASET")
print(len(cityZH[(cityZH['check'].isin(wikidataGM['check']) == False)].index.tolist()))
cityZH['bool'] = cityZH['check'].isin(wikidataGM['check'])

0    2018-12-31---Q693374
1    2017-12-31---Q693374
2    2016-12-31---Q693374
3    2015-12-31---Q693374
4    2014-12-31---Q693374
Name: check, dtype: object
NOT IN THE DATASET
3

In [7]:
cityZH

,id,name,date,population,wikidata_id,check,bool
0,123,Hirzenbach,2018-12-31,12801,Q693374,2018-12-31---Q693374,False
1,123,Hirzenbach,2017-12-31,12627,Q693374,2017-12-31---Q693374,True
2,123,Hirzenbach,2016-12-31,12463,Q693374,2016-12-31---Q693374,True
3,123,Hirzenbach,2015-12-31,11930,Q693374,2015-12-31---Q693374,True
4,123,Hirzenbach,2014-12-31,11679,Q693374,2014-12-31---Q693374,True
...,...,...,...,...,...,...,...
95,122,Schwamendingen-Mitte,1973-12-31,12118,Q692728,1973-12-31---Q692728,True
96,122,Schwamendingen-Mitte,1972-12-31,12465,Q692728,1972-12-31---Q692728,True
97,122,Schwamendingen-Mitte,1971-12-31,12738,Q692728,1971-12-31---Q692728,True
98,122,Schwamendingen-Mitte,1970-12-31,12849,Q692728,1970-12-31---Q692728,True
99,121,Saatlen,2018-12-31,8582,Q652455,2018-12-31---Q652455,False